### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by NessaSue**

### CODE REVIEW

**Comment by sirghiny** [comment]
Looks good to me. Check on the failing builds though.

**Comment by Arthur236** [comment]
### Index.html
* Use transparent overlay div to make the background dark
* Also, the Feature section should come before the About section, otherwise, the order of the links in the navbar should be changed

### Add.html
* Looks good. Though it would look better with a transparent overlay div to make the background dark

### Registration.html
* I think you should also have a background image on this page for consistency purposes

### View.html
* Still some issues with the text visibility for the titles.
* Again I insist on the transparent overlay

**Comment by Thuku** [comment]
- Good work on adding a descriptive readme.
- You checked on best practices for commit messages. plus for that
- Also plus on indenting your code.

**Comment by NessaSue** [comment]
I have made the suggested changes.

**Pull request merged**
